#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)"

# Set Docker/Kubernetes resource names managed by this script
basicAuthSecret="ffc-demo-basic-auth"
projectName="ffc-demo-web"

(
  cd "${projectRoot}"

  helm delete --purge \
    ${projectName}-redis \
    ${projectName}
)
