#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

command="$@"
projectName="ffc-demo-web-test"
service="ffc-demo-web"

# Default command to npm test script
if [ "${command}" = "" ]; then
  command="npm test"
fi

compose() {
  docker-compose -p "${projectName}" $@
}

(
  cd "${projectRoot}"

  # Guarantee clean environment
  compose down --volumes

  # Ensure container images are up to date
  compose build

  # Run tests
  compose run ${service} ${command}

  # Clean up
  compose down --volumes
)
